sudo: required
language: ruby
env: RACK_ENV=development
rvm:
 - 2.0.0
addons:
    code_climate:
      repo_token: 2deec4841978b14c5f8d2695508d4769837b5af8e585618235ab93295cd8321c
env: CODECLIMATE_REPO_TOKEN=2deec4841978b14c5f8d2695508d4769837b5af8e585618235ab93295cd8321c
services:
  - docker
before_install:
- docker pull ubuntu
- wget https://github.com/mumuki/mulang/releases/download/v0.2.5/mulang
- mv mulang bin/
- chmod +x bin/mulang
